config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :concerts
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :group, optional: true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, :dependent => :destroy
   
    enum membersgender: [:Man, :Woman, :Band]

    def to_s
        name
    end

    def total_concerts #total conciertos
        concerts.where(group_id: id).count
    end

    def attendance #asistentes
        concerts.where(group_id: id).map{|concert| concert.public}.sum
    end

    def last_concert #ultimo concierto
        concerts.where(group_id: id).map{|concert| concert.concert_date.strftime("%Y:%B:%A")}.last
    end

    def max_people #max de personas en un concierto
        concerts.pluck(:public).max
    end

    def max_duration #duracion max de un concierto
        concerts.pluck(:duration).max
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
    before_action :set_concert, only: %i[ show edit update destroy ]
  
    
    def index
      @concerts = Concert.all
    end
  
     
    def show
    end
  
    
    def new
      @concert = Concert.new
      @groups = Group.all
    end
  
   
    def edit
      @groups = Group.all
    end
  
    
    def create
      @concert = Concert.new(concert_params)
      @groups = Group.all
  
      respond_to do |format|
        if @concert.save
          format.html { redirect_to @concert, notice: "Concert was successfully created." }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
   
    def update
      respond_to do |format|
        if @concert.update(concert_params)
          format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    
    def destroy
      @concert.destroy
      respond_to do |format|
        format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      end
    end
  
    private
      
      def set_concert
        @concert = Concert.find(params[:id])
      end
  
      
      def concert_params
        params.require(:concert).permit(:public, :duration, :concert_date, :group_id)
      end
  end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :set_group, only: %i[ show edit update destroy ]
  
    # GET /groups 
    def index
      @groups = Group.all
      @concerts = Concert.all
    end
  
    # GET /groups/1 
    def show
    end
  
    # GET /groups/new
    def new
      @group = Group.new
      @concerts = Concert.all
    end
  
    
    def edit
    end
  
    
    def create
      @group = Group.new(group_params)
  
      respond_to do |format|
        if @group.save
          format.html { redirect_to @group, notice: "Group was successfully created." }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    
    def update
      respond_to do |format|
        if @group.update(group_params)
          format.html { redirect_to @group, notice: "Group was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    
    def destroy
      @group.destroy
      respond_to do |format|
        format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      end
    end
  
    private
     
      def set_group
        @group = Group.find(params[:id])
      end
  
     
      def group_params
        params.require(:group).permit(:name, :members, :membersgender)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :public, "Asistentes" %>
    <%= form.number_field :public %>
  </div>


  <div class="field">
    <%= form.label :duration, "Duración" %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :concert_date, "Fecha del Concierto" %>
    <%= form.date_select :concert_date %>
    
  </div>

  <div class="field">
    <%= form.label :group, "Grupo" %>
      <select name="concert[group_id]">
      <%  @groups.each do |group| %>
        <option value="<%= group.id %>"><%= group.name %></option>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table class="table mt-4">
  <thead class="table table-dark">
    <tr>
      <th class="text-center">Public</th>
      <th class="text-center">Duration</th>
      <th class="text-center">Concert date</th>
      <th class="text-center">Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td class="table-success"><%= concert.public %> personas</td>
        <td class="text-center"><%= concert.duration %> minutos</td>
        <td class="text-center"><%= concert.concert_date %></td>
        <td class="text-center"><%= concert.group %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back to Group', root_path %><br>
<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<div class="container"><h1>New Concert</h1>

    <%= render 'form', concert: @concert %>

    <%= link_to 'Back to Group', root_path %>
    <%= link_to 'Back', concerts_path %>
</div>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asistentes:</strong>
  <%= @concert.public %>
</p>

<p>
  <strong>Duración:</strong>
  <%= @concert.duration %>
</p>

<p>
  <strong>Fecha del Concierto:</strong>
  <%= @concert.concert_date %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @concert.group.name %>
</p>

<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Grupo" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :members, "Cantidad de Miembros" %>
    <%= form.number_field :members %>
  </div>

  <div class="field">
    <%= form.label :membersgender, "Tipo de Banda" %>
    <%= form.select :membersgender, Group.membersgenders.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table mt-4">
  <thead class="table table-dark">
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Members</th>
      <th class="text-center">Concerts</th>
      <th class="text-center">Total Attendees</th>
      <th class="text-center">Type Band</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
        <tr>
          <td class="table-primary"><%= group.name %></td>
          <td class="text-center"><%= group.members %></td>
          <td class="text-center"><%= group.total_concerts %></td> 
          <td class="text-center"><%= group.attendance %></td>
          <td class="text-center"><%= group.membersgender %></td>
          <td><%= link_to 'Show', group %></td>
          <td><%= link_to 'Edit', edit_group_path(group) %></td>
          <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Group', new_group_path %><br>
<%= link_to 'New Concert', new_concert_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Nombre del Grupo:</strong>
    <%= @group.name %>
  </p>

  <p>
    <strong>Miembros:</strong>
    <%= @group.members %>
  </p>

  <p>
    <strong>Último Concierto:</strong>
    <%= @group.last_concert %>
  </p>

  <p>
    <strong>Cantidad total de personas:</strong>
    <%= @group.max_people %> 
  </p>

  <p>
    <strong>Tiempo del Concierto:</strong>
    <%= @group.max_duration %>  minutos
  </p>

  <p>
    <strong>Tipo de Banda:</strong>
    <%= @group.membersgender %>
  </p>
  <%= link_to 'Edit', edit_group_path(@group) %> |
  <%= link_to 'Back', groups_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>